const recommendations=[
{type:'beach',title:'Bora Bora Beach',location:'French Polynesia',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',text:'Crystal-clear water, soft white sand, and beautiful tropical scenery make Bora Bora an unforgettable beach escape.'},
{type:'beach',title:'Clearwater Beach',location:'Florida, USA',image:'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=900&q=80',text:'A relaxing coastal destination known for sandy shores, warm water, sunsets, and water activities.'},
{type:'temple',title:'Kashi Vishwanath Temple',location:'Varanasi, India',image:'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=80',text:'A historic temple destination offering a rich cultural experience and fascinating architecture.'},
{type:'temple',title:'Fushimi Inari Shrine',location:'Kyoto, Japan',image:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80',text:'Famous for its thousands of red torii gates and peaceful mountain paths in Kyoto.'},
{type:'country',title:'France',location:'Paris, France',image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80',text:'Explore world-famous landmarks, historic cities, beautiful countryside, cuisine, and art.'},
{type:'country',title:'Japan',location:'Tokyo, Japan',image:'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=900&q=80',text:'Discover a unique blend of ancient traditions, modern cities, delicious food, and natural beauty.'}];
const results=document.getElementById('results'),input=document.getElementById('searchInput'),header=document.getElementById('resultsHeader');
function render(items,q=''){results.innerHTML=items.map(p=>`<article class="travel-card"><img src="${p.image}" alt="${p.title}"><div class="card-body"><span class="tag">${p.type}</span><h3>${p.title}</h3><p class="location">📍 ${p.location}</p><p>${p.text}</p><button class="details-btn">View Details</button></div></article>`).join('');header.innerHTML=q?`<h2>Search Results for "${q}"</h2><p>Here are some travel recommendations matching your search.</p>`:`<h2>Popular Recommendations</h2><p>Try searching for <b>beach</b>, <b>temple</b>, or <b>country</b>.</p>`}
function search(){const q=input.value.trim().toLowerCase();const matches=q?recommendations.filter(p=>p.type.includes(q)||p.title.toLowerCase().includes(q)||p.location.toLowerCase().includes(q)):recommendations;render(matches,q);document.getElementById('recommendations').scrollIntoView({behavior:'smooth'})}
document.getElementById('searchBtn').onclick=search;input.onkeydown=e=>{if(e.key==='Enter')search()};document.getElementById('clearBtn').onclick=()=>{input.value='';render(recommendations)};render(recommendations);
